# docker-compose.yml

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_SIP_DOMAIN: voiceai.wordpressstagingsite.com
      NEXT_PUBLIC_SIP_WEBSOCKET_URL: wss://voiceai.wordpressstagingsite.com/ws
      NEXT_PUBLIC_SIP_USERNAME: "1001"
      NEXT_PUBLIC_SIP_PASSWORD: "supersecret"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - asterisk

  nginx:
    image: nginx:1.25
    ports:
      - "443:443"
    depends_on:
      - app
      - asterisk
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/letsencrypt/live/voiceai.wordpressstagingsite.com:ro

  asterisk:
    image: andrius/asterisk:18
    container_name: asterisk
    restart: unless-stopped
    volumes:
      - ./asterisk/config:/etc/asterisk
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "8089:8089"    # <-- plain WS, nginx will TLS terminate
      - "10000-20000:10000-20000/udp"
    environment:
      - TZ=UTC
