# docker-compose.yml (local development)
version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules