# docker-compose.yml
version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - asterisk

  asterisk:
    image: andrius/asterisk:18   # ✅ lightweight prebuilt Asterisk
    container_name: asterisk
    restart: unless-stopped
    volumes:
      - ./asterisk/config:/etc/asterisk    # mount custom configs
      
    ports:
      - "5060:5060/udp"     # SIP
      - "5060:5060/tcp"     # SIP
      - "8089:8089"         # WebSocket (WSS for WebRTC)
      - "10000-20000:10000-20000/udp" # RTP (media)
    environment:
      - TZ=UTC
