[build]
# Use Docker build instead of custom build script
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Increase memory and timeout for build
[deploy.env]
RAILWAY_STATIC_URL = "true"

# Resource limits
[build.env]
# Set memory limits for build processes
NODE_OPTIONS = "--max_old_space_size=4096"
PYTHON_BUILD_MEMORY = "4GB"

# Auto-remove old containers
[experimental]
incrementalBuildCaching = true